function Prose({ children }: { children: React.ReactNode }) {
  return (
    <div className="flex flex-col gap-5 text-[15px] leading-[1.7] text-muted-foreground [&_h2]:mt-4 [&_h2]:text-[18px] [&_h2]:font-semibold [&_h2]:tracking-[-0.01em] [&_h2]:text-foreground [&_strong]:font-semibold [&_strong]:text-foreground [&_code]:rounded [&_code]:bg-border [&_code]:px-1 [&_code]:py-0.5 [&_code]:font-mono [&_code]:text-[13px] [&_code]:text-foreground [&_pre]:m-0 [&_pre]:overflow-x-auto [&_pre]:rounded-[var(--radius-lg)] [&_pre]:border [&_pre]:border-border [&_pre]:bg-background [&_pre]:p-4 [&_pre]:font-mono [&_pre]:text-[12.5px] [&_pre]:leading-[1.55] [&_pre]:text-foreground [&_pre_code]:bg-transparent [&_pre_code]:p-0 [&_pre_code]:text-[inherit] [&_p]:m-0 [&_ul]:m-0 [&_ul]:flex [&_ul]:list-disc [&_ul]:flex-col [&_ul]:gap-2 [&_ul]:pl-5 [&_li]:m-0">
      {children}
    </div>
  );
}

export function PostContent() {
  return (
    <Prose>
      <p>
        For the last decade, the consumer genome has been treated as something
        to look at.
      </p>
      <p>
        You logged into a portal. You downloaded a PDF. You saw a list of
        traits, a set of risk reports, and a handful of variants with cautious
        explanations. If you were technical, you might also receive a VCF: the
        raw material of your genome, stored in a format built for sequencing
        pipelines rather than software agents.
      </p>
      <p>The genome became a result.</p>
      <p>It should have become a workspace.</p>
      <p>
        Today, The Genome Computer Company is opening early access to Genome
        Computer for Codex: a remote MCP server that lets Codex work with
        authorised genomic context from a user's Genome Computer account.
      </p>

      <h2>Why Codex</h2>
      <p>Chat is the right surface for answers. Codex is the right surface for work.</p>
      <p>
        A <code>.genome/1.0</code> bundle contains typed tables,
        manifest-declared rules, pharmacogenomic calls, polygenic scores,
        provenance hashes, and the originating VCF as a sovereignty layer. It
        can be queried. It can be validated. It can be turned into reports,
        dashboards, notebooks, apps, and clinical handoff documents.
      </p>
      <p>That is what Codex is built for.</p>

      <h2>What it does</h2>
      <p>Genome Computer for Codex exposes a remote MCP endpoint:</p>
      <pre>
        <code>https://mcp.genome.computer/mcp</code>
      </pre>
      <p>
        Users add it to Codex, sign in with their Genome Computer account,
        choose the ready <code>.genome</code> bundle to use by default, and
        approve access.
      </p>
      <p>From that point on, Codex can use Genome Computer when a task needs genomic context.</p>
      <ul>
        <li>Validate this <code>.genome</code> bundle and tell me what failed.</li>
        <li>Summarise my pharmacogenomic findings for a clinician.</li>
        <li>Show my polygenic score table.</li>
        <li>Generate a report I can rerun when the bundle updates.</li>
      </ul>

      <h2>Why the index matters</h2>
      <p>
        The authoritative deliverable remains the full <code>.genome.tar.gz</code>
        bundle. The MCP server reads a compact sidecar index generated by the
        conversion pipeline, so agent calls are fast, bounded, and safe.
      </p>
      <p>
        Chat turns genome data into an answer. Codex turns genome data into a
        reproducible workflow.
      </p>

      <h2>The privacy boundary</h2>
      <p>
        Genomic data is not ordinary user data. Genome Computer for Codex is
        account-authorised, scoped, and revocable. The default tools expose
        structured context and indexed results, not a blanket dump of raw
        genetic files to every connected client.
      </p>

      <h2>Request access</h2>
      <p>
        Genome Computer for Codex is in early access. We are looking for
        builders working on clinical, consumer, research, and agent-based
        products that need direct, auditable access to genomic context.
      </p>
    </Prose>
  );
}
