import {
  loadBundleForEmail,
  loadMcpIndex,
  listReadyBundlesForEmail,
  signBundleDownloadUrl,
  type GenomeMcpIndex,
} from "@/lib/genome/bundles";
import type { McpAuthContext } from "./auth";

export const MCP_PROTOCOL_VERSION = "2025-06-18";

type JsonRpcRequest = {
  jsonrpc: "2.0";
  id?: string | number | null;
  method: string;
  params?: unknown;
};

type JsonRpcResponse = {
  jsonrpc: "2.0";
  id: string | number | null;
  result?: unknown;
  error?: { code: number; message: string; data?: unknown };
};

export type DispatchResult = { response: JsonRpcResponse | null };

const TOOL_DEFS = [
  {
    name: "list_genome_bundles",
    title: "List available .genome bundles",
    description:
      "List ready .genome bundles connected to this Genome Computer account. Call this before querying when the user has multiple bundles or has not specified one.",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
  },
  {
    name: "get_genome_manifest",
    title: "Get .genome manifest",
    description:
      "Return the manifest and provenance metadata for a .genome bundle. Use this for questions about schema version, pipeline version, reference build, source versions, and reproducibility.",
    inputSchema: {
      type: "object",
      properties: { bundle_id: { type: "string" } },
      additionalProperties: false,
    },
  },
  {
    name: "validate_genome_bundle",
    title: "Validate .genome bundle",
    description:
      "Return the latest validation report for a .genome bundle, including schema, manifest, and hash checks generated by the conversion pipeline.",
    inputSchema: {
      type: "object",
      properties: { bundle_id: { type: "string" } },
      additionalProperties: false,
    },
  },
  {
    name: "get_pgx_profile",
    title: "Get pharmacogenomics profile",
    description:
      "Return gene-level pharmacogenomic calls from pharmacogenomics.parquet. Use for CYP genes, CPIC/PharmCAT phenotypes, diplotypes, and drug-gene context. Do not provide dosing instructions.",
    inputSchema: {
      type: "object",
      properties: { bundle_id: { type: "string" }, gene: { type: "string" } },
      additionalProperties: false,
    },
  },
  {
    name: "query_genome",
    title: "Run a constrained genome query",
    description:
      "Run an approved query over the MCP index for a .genome bundle. Supported queries: pgx_phenotypes, polygenic_scores, gene_summary.",
    inputSchema: {
      type: "object",
      properties: {
        bundle_id: { type: "string" },
        query: { type: "string", enum: ["pgx_phenotypes", "polygenic_scores", "gene_summary"] },
        gene: { type: "string" },
      },
      required: ["query"],
      additionalProperties: false,
    },
  },
  {
    name: "generate_genome_report",
    title: "Generate a genome report",
    description:
      "Return a precomputed report summary for a .genome bundle, plus a signed bundle download URL for deeper local analysis. Use for clinician-facing or user-facing summaries.",
    inputSchema: {
      type: "object",
      properties: {
        bundle_id: { type: "string" },
        audience: { type: "string", enum: ["clinician", "user"] },
      },
      additionalProperties: false,
    },
  },
] as const;

const SERVER_INSTRUCTIONS = `You have access to the user's Genome Computer .genome workbench.

Use these tools when the user asks about their genome as data: bundle validation, provenance, pharmacogenomics, polygenic scores, gene summaries, or report generation.

Always query the tools for claims about the user's genome. Do not infer clinical diagnoses or dosing instructions. Frame findings as data in a dated .genome bundle, cite provenance when available, and recommend clinician confirmation for medical decisions.`;

export async function dispatchMcpMessage(
  body: unknown,
  ctx: McpAuthContext,
): Promise<DispatchResult> {
  const req = body as JsonRpcRequest;
  if (!req || typeof req !== "object" || req.jsonrpc !== "2.0" || typeof req.method !== "string") {
    return { response: errorResponse(null, -32600, "Invalid JSON-RPC request") };
  }
  const id = req.id === undefined || req.id === null ? null : req.id;

  switch (req.method) {
    case "initialize":
      return ok(id, {
        protocolVersion: MCP_PROTOCOL_VERSION,
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: "genome-computer-mcp", version: "0.1.0" },
        instructions: SERVER_INSTRUCTIONS,
      });
    case "notifications/initialized":
    case "notifications/cancelled":
      return { response: null };
    case "ping":
      return ok(id, {});
    case "tools/list":
      return ok(id, { tools: TOOL_DEFS.map(toToolEntry) });
    case "tools/call":
      return handleToolCall(id, req.params, ctx);
    default:
      return { response: errorResponse(id, -32601, `Method not found: ${req.method}`) };
  }
}

function toToolEntry(tool: (typeof TOOL_DEFS)[number]) {
  return {
    name: tool.name,
    title: tool.title,
    description: tool.description,
    inputSchema: tool.inputSchema,
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  };
}

async function handleToolCall(
  id: string | number | null,
  params: unknown,
  ctx: McpAuthContext,
): Promise<DispatchResult> {
  const call = params as { name?: unknown; arguments?: unknown };
  if (!call || typeof call.name !== "string") {
    return { response: errorResponse(id, -32602, "Invalid tools/call params") };
  }
  const args = (call.arguments ?? {}) as Record<string, unknown>;
  try {
    switch (call.name) {
      case "list_genome_bundles": {
        const bundles = await listReadyBundlesForEmail(ctx.email);
        return toolResult(id, { bundles });
      }
      case "get_genome_manifest": {
        const { bundle, index } = await requireIndex(ctx, args);
        return toolResult(id, {
          bundle,
          manifest: index.manifest ?? null,
          note: index.manifest ? undefined : "No manifest was present in the MCP index.",
        });
      }
      case "validate_genome_bundle": {
        const { bundle, index } = await requireIndex(ctx, args);
        return toolResult(id, {
          bundle,
          validation: index.validation ?? null,
          valid: Boolean((index.validation as { valid?: unknown } | undefined)?.valid),
        });
      }
      case "get_pgx_profile": {
        const { bundle, index } = await requireIndex(ctx, args);
        const gene = typeof args.gene === "string" ? args.gene.toUpperCase() : null;
        const rows = filterByGene(index.pharmacogenomics ?? [], gene);
        return toolResult(id, { bundle, gene, pharmacogenomics: rows });
      }
      case "query_genome": {
        const { bundle, index } = await requireIndex(ctx, args);
        const query = args.query;
        if (query === "pgx_phenotypes") {
          return toolResult(id, { bundle, rows: index.pharmacogenomics ?? [] });
        }
        if (query === "polygenic_scores") {
          return toolResult(id, { bundle, rows: index.polygenic_scores ?? [] });
        }
        if (query === "gene_summary") {
          const gene = typeof args.gene === "string" ? args.gene.toUpperCase() : null;
          return toolResult(id, { bundle, gene, rows: filterByGene(index.gene_index ?? [], gene) });
        }
        return { response: errorResponse(id, -32602, "Unsupported query") };
      }
      case "generate_genome_report": {
        const { bundle, index } = await requireIndex(ctx, args);
        const audience = args.audience === "clinician" ? "clinician" : "user";
        const signed_bundle_url = await signBundleDownloadUrl(bundle);
        return toolResult(id, {
          bundle,
          audience,
          report_markdown:
            audience === "clinician"
              ? index.reports?.clinician_summary_markdown ?? fallbackReport(index)
              : index.reports?.user_summary_markdown ?? fallbackReport(index),
          signed_bundle_url,
          signed_bundle_url_expires_in_seconds: signed_bundle_url ? 900 : null,
        });
      }
      default:
        return { response: errorResponse(id, -32601, `Unknown tool: ${call.name}`) };
    }
  } catch (err) {
    return {
      response: errorResponse(
        id,
        -32603,
        err instanceof Error ? err.message : "Internal server error",
      ),
    };
  }
}

async function requireIndex(ctx: McpAuthContext, args: Record<string, unknown>) {
  const requested = typeof args.bundle_id === "string" ? args.bundle_id : ctx.defaultBundleId;
  const bundle = await loadBundleForEmail(ctx.email, requested);
  if (!bundle) throw new Error("No ready .genome bundle found for this account.");
  const index = await loadMcpIndex(bundle);
  if (!index) {
    throw new Error(
      "This bundle is ready, but its MCP query index has not been generated yet. Regenerate or backfill the bundle MCP index.",
    );
  }
  return { bundle, index };
}

function filterByGene(rows: unknown[], gene: string | null): unknown[] {
  if (!gene) return rows;
  return rows.filter((row) => {
    if (!row || typeof row !== "object") return false;
    const value =
      (row as Record<string, unknown>).gene_symbol ??
      (row as Record<string, unknown>).gene ??
      (row as Record<string, unknown>).symbol;
    return typeof value === "string" && value.toUpperCase() === gene;
  });
}

function fallbackReport(index: GenomeMcpIndex): string {
  const manifest = index.manifest ?? {};
  const generated = String(manifest.generated_at ?? index.generated_at ?? "unknown");
  const schema = String(manifest.schema_version ?? "unknown");
  return [
    "# Genome Computer .genome Summary",
    "",
    `Generated at: ${generated}`,
    `Schema version: ${schema}`,
    `Pharmacogenomics rows: ${(index.pharmacogenomics ?? []).length}`,
    `Polygenic score rows: ${(index.polygenic_scores ?? []).length}`,
    "",
    "This summary is generated from a dated .genome bundle. It is data, not a diagnosis; clinical decisions require clinician confirmation.",
  ].join("\n");
}

function toolResult(id: string | number | null, data: unknown): DispatchResult {
  return ok(id, { content: [{ type: "text", text: JSON.stringify(data, null, 2) }] });
}

function ok(id: string | number | null, result: unknown): DispatchResult {
  return { response: { jsonrpc: "2.0", id, result } };
}

function errorResponse(
  id: string | number | null,
  code: number,
  message: string,
  data?: unknown,
): JsonRpcResponse {
  return { jsonrpc: "2.0", id, error: { code, message, ...(data ? { data } : {}) } };
}
